name: README Repos List
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: Run readme-repos-list
        uses: DenverCoderOne/readme-repos-list@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          query: "user:DenverCoderOne fork:true"
          max: 100
          sort: "name"
