name: README Repos List CI
on:
  workflow_dispatch:
jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: Run readme-repos-list
        uses: koj-co/readme-repos-list@master
        with:
          token: ${{ secrets.GH_PAT }}
          query: "DenverCoderOne in:readme"
          max: 10
